const TYPES = {
  auth: {
    USER_LOAD_START: "USER_LOAD_START",
    USER_LOAD_SUCCESS: "USER_LOAD_SUCCESS",
    USER_LOAD_FAIL: "USER_LOAD_FAIL",
    USER_LOGIN: "USER_LOGIN",
    USER_REGISTER: "USER_REGISTER",
    USER_LOGOUT: "USER_LOGOUT"
  },
  leads: {
    GET_LEADS: "GET_LEADS",
    DELETE_LEAD: "DELETE_LEAD",
    POST_LEAD: "POST_LEAD",
    UNDO_DELETE: "UNDO_DELETE",
    LEADS_ERROR: "LEADS_ERROR"
  },
  notifications: {
    ENQUEUE_SNACKBAR: "ENQUEUE_SNACKBAR",
    CLOSE_SNACKBAR: "CLOSE_SNACKBAR",
    REMOVE_SNACKBAR: "REMOVE_SNACKBAR"
  }
};

export default TYPES;
